spring.application.name=forsight-backend
server.port=8080

# PostgreSQL Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# API Keys & Microservices
gemini.api.key=${GEMINI_KEY}
grok.api.key=${GROK_API_KEY}
ml.service.url=${ML_URL}