spring.application.name=forsight-backend
server.port=8080

# PostgreSQL Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate / JPA
# Set to 'none' as we use explicit schema.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# API Keys & Microservices
gemini.api.key=${GEMINI_KEY}
ml.service.url=${ML_URL}